baseURL = "https://xiongdahu.github.io"
defaultContentLanguage = "en"
title = "香取"
LanguageCode = "zh-CN"
Theme =  "next"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "monokai"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
DefaultContentLanguage = "zh"

[Params]
  homeSubtitle = "香取海"
  Introduce = "the craft of programming"
  Description = "编程是一门手艺"
  Keywords =  "读书,思考,代码,架构,JVM,Java,Clojure,Scala,Python"
  Subtitle = "胆小认生,沉默寡言"
  Imglogo = "/img/logo.png"
  AuthorImg = "/img/author.jpg"
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
  #BaiduStatsId = "0b07433b4ab8d587dae7d34e71973839"
  Fancybox = true
  summaryLength = 0

[Author]
  Name = "熊打虎"

[Params.Share]
  #DuoShuo = "xxx"
  #Baidu = true

[[Menu.Main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "归档"
  Pre = "archive"
  URL = "/post/"
  Weight = 2
[[Menu.Main]]
  Name = "编程"
  Pre = "code"
  URL = "/categories/编程/"
  Weight = 3

[[Menu.Main]]
  Name = "关于"
  Pre = "user"
  URL = "/about/"
  Weight = 8

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/xiongdahu/"
[[Params.Socials]]
  Name = "知乎"
  Icon = "globe"
  URL = "https://www.zhihu.com/people/boris-hsiung"  
